# Generated by Django 3.2.4 on 2021-06-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=40)),
                ('author_name', models.CharField(max_length=40)),
                ('course_date', models.DateField()),
                ('course_price', models.FloatField()),
                ('users_enrolled', models.CharField(max_length=200)),
            ],
        ),
    ]
