# Generated by Django 3.2.4 on 2021-06-20 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseWebapp', '0006_courses_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='name',
            new_name='category',
        ),
    ]
