# Generated by Django 3.2.4 on 2021-06-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseWebapp', '0007_rename_name_courses_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='category',
            new_name='name',
        ),
    ]
