# Generated by Django 3.2.4 on 2021-06-20 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseWebapp', '0008_rename_category_courses_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courseWebapp.category'),
        ),
    ]
